ALTER TABLE crawl_jobs
  ADD COLUMN IF NOT EXISTS include_paths JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS exclude_paths JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS regex_on_full_url BOOLEAN NOT NULL DEFAULT FALSE;
